In [1]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

df = pd.read_csv('outletData/featureData/all_outlets_feature.csv', sep=' ')
df = df.sample(frac=1).reset_index(drop=True)
df = df.head(50)
X = df.drop(columns=["Outlet"])
y = df["Outlet"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
df

    AverageFlow  Volume  Duration          Outlet
0    170.384615    2215        14  washingMachine
1     32.625000     261         9   washroomBasin
2     16.363636     360        23   washroomBasin
3     79.307692    3093        41      showerHead
4    103.923077    1351        14    kitchenBasin
5     46.520000    3489        81   washroomBasin
6     20.100000     201        10    kitchenBasin
7    176.416667    2117        13  washingMachine
8     15.857143     111         8   washroomBasin
9     23.714286     166         7   washroomBasin
10    22.700000     227        11    kitchenBasin
11   154.285714    2160        15  washingMachine
12    92.940141   26395       305      showerHead
13    37.111111     334        10   washroomBasin
14    54.818182     603        12    kitchenBasin
15   179.000000    6086        36  washingMachine
16    31.436364    1729        58    kitchenBasin
17   177.280000    8864        53  washingMachine
18    11.000000      88         8   washroomBasin
19    36.666667     440        13    kitchenBasin
20   190.214286    2663        14  washingMachine
21    46.250000     925        21   washroomBasin
22    24.692308     321        14   washroomBasin
23    15.076923     392        28   washroomBasin
24    13.344828     387        34   washroomBasin
25    93.461538    1215        14    kitchenBasin
26    37.160000     929        27   washroomBasin
27    77.111111     694        10   washroomBasin
28    51.666667     310         7   washroomBasin
29    70.333333    1688        25   washroomBasin
30    64.678571   18110       297      showerHead
31    19.411765     330        18   washroomBasin
32    35.750000    1430        42    kitchenBasin
33    65.930233    5670        91      showerHead
34    29.166667     175         7   washroomBasin
35    59.866667     898        16    kitchenBasin
36    53.705882    1826        36    kitchenBasin
37    10.964286     307        30   washroomBasin
38    58.750000     470         8    kitchenBasin
39    11.666667      70         6   washroomBasin
40    25.833333     155         6   washroomBasin
41    27.500000     165         7    kitchenBasin
42   165.142857    3468        22  washingMachine
43   141.750000    2835        21    kitchenBasin
44    40.125000     321         8    kitchenBasin
45    57.951220    2376        43    kitchenBasin
46    27.666667     166         8    kitchenBasin
47   171.571429    3603        22  washingMachine
48    67.125000     537         8   washroomBasin
49    63.431034    3679        62   washroomBasin

In [2]:
model = DecisionTreeClassifier()
model.fit(X_train,y_train)

DecisionTreeClassifier()

In [3]:
predictions = model.predict(X_test)
accuracy_score(y_test, predictions)

0.6

In [7]:
from sklearn import svm
from sklearn.metrics import classification_report

svm_model = svm.SVC(kernel='poly', gamma='auto', C=1, verbose=True, max_iter=10)

# svm_predictions = svm_model.predict(X_test)
# print(classification_report(y_test, svm_predictions))

In [ ]:
svm_model.fit(X_train,y_train)

[LibSVM]

In [6]:
predictions = svm_model.predict(X_test)
accuracy_score(y_test, predictions)

0.7